### ISSUE TITLE
Provide a NuGet package

### ISSUE THREAD

**Issue by marce155** [electricessence/TypeScript.NET#10]
Found this today and it seems to have the potential to replace my homegrown pseudo-collections :)
**Thanks a lot for your work!**

Two remarks:
- I think the Collections + LINQ part is the most important one, please make sure it is rock solid and complete before moving over to other .NET classes
- Please consider offering this as NuGet package, I've gotten addicted to it and can't add libs on my own anymore ;)

**Comment by electricessence** [comment]
Just an update.  This may need some more .nuget configration but currently it works with bower.
Any suggestions would be appreciated.

**Comment by marce155** [comment]
Wow, just saw you are putting a lot of effort into this lately, best of luck! Have you considered pinging Jon Galloway for a possible highlight in the next ASP.NET community standup or so?

Sadly, I haven't worked a lot with bower so far, just never had the opportunity. So I’m not exactly sure how bower compatibility helps with a nuget package? Or are you suggesting bower as the better alternative?

**Comment by electricessence** [comment]
Oh wow.  Yeah.  That's a great idea.  I'm all for it.  I'm gonna get this .nuget package up and running soon!  How can I contact Jon?  I've been peering in on the ASP.net standups, but not all the time.

**Comment by electricessence** [comment]
https://www.nuget.org/packages/TypeScript.NET.AMD/

And done. :)
Please help spread the word.  Let's make the most awesome TS/JS library ever! :)
