### ISSUE TITLE
Code review of XObject

### ISSUE THREAD

**Issue by electricessence** [electricessence/TypeScript.NET#14]
XObject was just checked in at the level of which the .NET framework implements it.
https://github.com/electricessence/TypeScript.NET/blob/develop-%28System.Xml.Linq%29/System.Xml.Linq/XObject.ts

It uses EventDispatcher and a new class called EventHelper to manage changing and changed events.
Please review the XObject code since it will be a significant class for the rest of the System.Xml.Linq namespace.

**Comment by electricessence** [comment]
The XLinq.cs file is included for reference.

**Comment by agnauck** [comment]
looks good to me, I found no issues

**Comment by electricessence** [comment]
Great.  I'll keep going from here.   Was working on how to implement XmlConvert to make sure it matches what .NET does.  Once that is done, then I can continue with XAttribute.
