### ISSUE TITLE
Is there any chance this will apper on bower in near future?

### ISSUE THREAD

**Issue by Mistrall** [electricessence/TypeScript.NET#18]
Really like if this lib can be managed through bower packager infra

**Comment by electricessence** [comment]
I've made it bower friendly now.  You should be able to point bower to the master branch.
I'm not sure what else I need to do to get it to show up in the bower search.
Any suggestions?

**Comment by electricessence** [comment]
This is officially on bower now.
```
bower install TypeScript.NET
```
