### ISSUE TITLE
How about a TryCast method?

### ISSUE THREAD

**Issue by scuzzlebuzzle** [electricessence/TypeScript.NET#20]
How about a TryCast method? Could be useful with ajax and unknown types... Also, just wanted to say this project is awesome and mind boggling that the community hasn't migrated here yet.

**Comment by electricessence** [comment]
Thanks!!! I've been really pushing up the quality lately to improve the likely-hood of adoption.
Please promote!  I've really put my heart into this as best I can as one person.
TryCast?  Can you elaborate?

**Comment by electricessence** [comment]
@scuzzlebuzzle :  Still confused about what you're asking with TryCast.
