### ISSUE TITLE
Javascript files in source directory

### ISSUE THREAD

**Issue by thefabulousdev** [electricessence/TypeScript.NET#25]
Shouldn't all the compiled TypeScript files reside on dist?

**Comment by electricessence** [comment]
I've struggled with how to appropriately do this.  Any suggestions for improvement are hugely welcome.

```dist``` *DOES* have all the compiled files.  But when you are looking to use the TypeScript files in your project, it seems easier to point to ```source```.

**Comment by electricessence** [comment]
Also note that the JS files in the ```source``` directory use UMD modules so they can be easily imported from NodeJS or RequireJS, or... whatever...

**Comment by electricessence** [comment]
@thefabulousdev, feel free to reopen if you want to discuss more.
