### ISSUE TITLE
Confusing repository description

### ISSUE THREAD

**Issue by thefabulousdev** [electricessence/TypeScript.NET#26]
"A JavaScript Friendly .NET Based Library Ported to TypeScript"

Implies that its a port of an already existing "Javascript-Friendly .NET Based library" to TypeScript.

**a)** If the library **IS** a port to TypeScript of an existing "JavaScript Friendly .NET Based library" the name of this library should be mentioned in the description and be read as "A TypeScript port of ${LibraryName}"

**b)** If the library **IS NOT** a port of an existing "JavaScript Friendly .NET Based library", but a port of .NET to TypeScript the description should be something like "A TypeScript port of .NET".

**Comment by electricessence** [comment]
Ok I've removed the 'Ported' text for now until I think of something better. :)
It's not really a **port** until all the .NET code is there.  And the way things are going, it will never be 1-to-1 so better just say 'based'.

**Comment by electricessence** [comment]
7f1c857264695d9f75b7272a53bd298eb172d613
