### ISSUE TITLE
Minimal setup?

### ISSUE THREAD

**Issue by marce155** [electricessence/TypeScript.NET#28]
I'm starting a new project and would like to include TypeScript.NET.

What's the minimal setup needed to use it? The NuGet package installed source and dist folders. I would like to just have it sit under Scripts in a single folder.
What things do I have to delete and move to use the full library with a minimal number of files?

**Comment by electricessence** [comment]
I want to be sure this process for you is as easy as possible, so please keep in contact until this is resolved.

TypeScript.NET has many files and inner dependencies that you may or may not need in your project.  Originally it was built as monoliths, but after a time, modularity became necessary.
Please read and comment here too: https://github.com/electricessence/TypeScript.NET/issues/25

TypeScript.NET is best used with TypeScript.   You can use the compiler to the compile the source into a single file including only the files you used.  Or even better, you can use your favorite module loader to import them at run-time.  If you need to bundle files, it's recommended to use r.js optimizer.

If you are using only JavaScript and want to use the library without types, then the dist folder is there for that purpose.  In a web project, using RequireJS and dist/amd will work very well.

Please let me know if you still have questions.

**Comment by electricessence** [comment]
I have yet to try browserify, but many people use that.

**Comment by electricessence** [comment]
@marce155, feel free to reopen if you want to discuss more.
