### ISSUE TITLE
Constraint of a type parameter cannot reference any type parameter from the same type parameter list.

### ISSUE THREAD

**Issue by Acentrage** [electricessence/TypeScript.NET#33]
Constraint of a type parameter cannot reference any type parameter from the same type parameter list.

I'm getting this error in Visual Studio for ILinkedNodeList, ILinkedNode and assertValidDetached. 

I fixed it by replacing "TNode" with "any":

    interface ILinkedNodeList<TNode extends ILinkedNode<TNode>>
    interface ILinkedNodeList<TNode extends ILinkedNode<any>>

Any other solutions or should I create a PR?

Visual Studio 2015, Update 1
TypeScript 1.7.6.0

**Comment by electricessence** [comment]
K.   Just a note, I'm using 1.8.7  and this code was updated in the last month.  Lemme do a bit more investigating.  What about only changing the code on the assertion function?

**Comment by electricessence** [comment]
Yeah, so that function is effectively private, so we could change anything to any.
If you change that, but keep the interface the way it was, does the error go away?
