### ISSUE TITLE
Doesn't build.

### ISSUE THREAD

**Issue by mhsimkin** [electricessence/TypeScript.NET#40]
I installed the Nuget package TypeScript.NET.Library  into my project.  When I try to build, it is looking for a node.ts file.  There are 4 *.d.ts in the node package. 

1) What version of the node.ts file am I supposed to load?
2) Please make this a dependency of the Nuget Package.

Thanks

**Comment by electricessence** [comment]
I'll need more information.
Can you explain how you are using the library?
Are you writing TS that uses the source folder?

What kind of project are you building?

**Comment by mhsimkin** [comment]
Just close this issue.  I went in a different direction. 

Thanks

marc

**Comment by electricessence** [comment]
Ok.  In the future, you may find using NPM would work better.
