### ISSUE TITLE
Sample on how to use the Event classes

### ISSUE THREAD

**Issue by mhsimkin** [electricessence/TypeScript.NET#41]
Can you please provide a sample on how to use the event classes?  There are no tests in the repo that can provide a reference point.

Thanks

marc

**Comment by electricessence** [comment]
For reference:
https://github.com/electricessence/TypeScript.NET/tree/master/source/System/Events

**Comment by electricessence** [comment]
Ok so the basis for the event classes is similar to how the DOM has events as well as how the original Flash and Dart event dispatchers work.

Except for EventSimple, which doesn't require a string registry of events.  It simply **IS** and event.  And much like an Observer style object, can 'dispatch' a signal.

**Comment by electricessence** [comment]
Example 1:

```ts
var es = new EventSimple();
ex.add((x,y,z)=>{/* some stuff */});
ex.add((x,y,z)=>{/* some stuff */});
/* time goes by */
ex.dispatch(x,y,z);
/* All done? */
ex.dispose();
```

**Comment by electricessence** [comment]
Example 2:
```ts
const EVENT_A = "eventNameA", EVENT_B = "eventNameB";
var ed = new EventDispatcherBase();
ed.addEventListener(EVENT_A,()=>{/* do something */});
ed.addEventListener(EVENT_B,()=>{/* do something */});
/* time goes by */
ed.dispatch(EVENT_A);
ed.dispatch(EVENT_B);
/* All done? */
ed.dispose();
```

**Comment by electricessence** [comment]
The obvious alternatives are Observable classes where you 'subscribe' and 'unsubscribe':
https://github.com/electricessence/TypeScript.NET/tree/master/source/System/Observable

**Comment by electricessence** [comment]
And another alternative:
https://github.com/electricessence/TypeScript.NET/blob/master/source/System/Collections/Array/Dispatch.ts

**Comment by electricessence** [comment]
@mhsimkin: Lemme know if that answered your question.

**Comment by mhsimkin** [comment]
Thank you.  This is very helpful.
