### ISSUE TITLE
module load error in VS2015 node console application

### ISSUE THREAD

**Issue by GaikwadPratik** [electricessence/TypeScript.NET#47]
Hi,

I'm following the steps that you had shown in the video. However I'm using VS2015 instead of  WebPack. I'm trying to use the library in a console nodejs project in VS2015. I've installed the library using npm. However it is giving me below error. 

**_Error	TS2307	Cannot find module 'typescript-dotnet-umd/dist/es6/System.Linq/Linq'._**

Could you please help me out here in resolving the error? 

Also can you please update the documentation with examples from JSON and other functions such as where, find, filter etc?

**Comment by electricessence** [comment]
First thing...
This is invalid.
```typescript-dotnet-umd/dist/es6/System.Linq/Linq```

This should work:
```typescript-dotnet-umd/System.Linq/Linq```

But there's a curiosity... Do you want to use es6?
Then change your dependencies to the es6 dist:
```typescript-dotnet-es6/System.Linq/Linq```

**Comment by GaikwadPratik** [comment]
I figured that out. If possible can you correct the documentation at below link?

https://github.com/electricessence/TypeScript.NET/tree/master/source/System.Linq

Also can you please explain what is the difference between umd and es6 modules?

**Comment by electricessence** [comment]
https://github.com/electricessence/TypeScript.NET/commit/da1f7b047a5e39dcf617f24e4498e74ff8cf25d4
Fixed this.

**Comment by electricessence** [comment]
Sorry that it was out of date. :(

**Comment by electricessence** [comment]
Sure...
https://www.youtube.com/watch?v=kCmjN5_wVZU

ES6 isn't compatible (yet) with everything.  But if you are doing a NodeJS console project, then it's a great way to go if you have the latest NodeJS version that is ES6 compatible.  And you'll obviously be able to happily leverage Async/Await :)

UMD is compatible with both Node (CommonJS) and Web (AMD and static loading).

**Comment by electricessence** [comment]
Did I answer all your questions and resolve all your issues?

**Comment by GaikwadPratik** [comment]
Yes. Thank you for clarifying the all the doubts. and It's an awesome library that you have written.

**Comment by electricessence** [comment]
@GaikwadPratik Thanks!  It helps me too. :)  I'm just glad there's even 1 person else that it helps.
