### ISSUE TITLE
Resharper Conflict

### ISSUE THREAD

**Issue by lommez** [electricessence/TypeScript.NET#48]
I'm using Resharper 2016.2.2 and for unknown reason after added the typescript.net in my project the Visual Studio crash.
Anyone else is having the same issue?  Is that a known bug?
The only temporally solution for that is to disable the Resharper.

**Comment by electricessence** [comment]
@lommez Will look into ASAP.  But I don't have an instance of Resharper.

**Comment by lommez** [comment]
@electricessence , today i've enabled ReSharper again, and it is working fine.
I think that fix is something related to the last library updates

**Comment by electricessence** [comment]
@lommez Ok!  That is great to hear!
