### ISSUE TITLE
Errors to build project

### ISSUE THREAD

**Issue by lommez** [electricessence/TypeScript.NET#49]
I can't build my project. 
I'm attaching here an image showing the errors.
[https://portalvhdsdtx1sqp9m14cf.blob.core.windows.net/vhds/TypeScriptNet_Errors.jpg](url)

It looks like it's missing some files.

**Comment by electricessence** [comment]
@lommez Will look into ASAP.

**Comment by electricessence** [comment]
There looks to have been some missing files from check-in to GitHub but I'm not sure if that is affecting you.
Could you try again with updated 4.0.1 and see if you still have the same issue?
I'm available today to fix this.

**Comment by lommez** [comment]
Hi @electricessence ,
Thanks for quick reply.
I'm going to try with the new version.
Is already available in github?

**Comment by electricessence** [comment]
@lommez One moment.  Publishing and verifying.

**Comment by lommez** [comment]
Thanks @electricessence

**Comment by electricessence** [comment]
@lommez Ok everything looks good.  Try now.
How have you been getting the files?

**Comment by electricessence** [comment]
Are you getting the entire GitHub repo or are you using NPM?

**Comment by lommez** [comment]
I'm getting the entire GitHub

**Comment by electricessence** [comment]
@lommez Is there a reason why?
How are you using in your project?
The most common way to integrate is by using NPM and picking a specific dist...

**Comment by lommez** [comment]
No specific reason for that.
Even using Visual Studio the best way is to use the NPM package?

**Comment by electricessence** [comment]
@lommez So it's based upon your use case really.  But typically speaking, let's say you are developing a NodeJS project.
Then I'm guessing it would be more straight forward to simply
npm install typescript-dotnet-commonjs --save
instead of pulling manually from GitHub.

This is also true for web projects, you could easily
npm install typescript-dotnet-umd --save

Or you could use Bower which I believe is integrated with VS.

The other way is to simply cherry pick the
dist
you need and include it in your project.  But as you can imagine that will be problematic to update later.

**Comment by electricessence** [comment]
I'll need to update the release for Bower (doing now).

**Comment by lommez** [comment]
In my case, i'm developing web project and my application is using requirejs.
I'll try to install it by using the command:
npm install typescript-dotnet-commonjs --save

**Comment by electricessence** [comment]
Don't do that

**Comment by electricessence** [comment]
If you are using requirejs then use the AMD dist specifically.

**Comment by electricessence** [comment]
```npm install typescript-dotnet-amd --save```
https://www.npmjs.com/package/typescript-dotnet-amd

**Comment by electricessence** [comment]
That way you are leveraging an already minified and web ready version.

**Comment by lommez** [comment]
Thank you for the advice

**Comment by electricessence** [comment]
No problem!

**Comment by electricessence** [comment]
If you are familiar with RequireJS then this should work very nicely with your project.
All classes are separate modules and load on demand.
If you intend on using LINQ then note that
```linqAsync(callback?: (linq: ILinqEnumerable<T>) => void): ILinqEnumerable<T>;```
exists as part of CollectionBase.
So you can call it at anytime to dynamically load the LINQ extensions.
Once that has resolved the first time, you can then call ```.linq``` from then on.

**Comment by electricessence** [comment]
Please let me know if this fixes your issue.

**Comment by lommez** [comment]
The npm packages are done?

**Comment by electricessence** [comment]
Yes they are up.  Is that your question?

**Comment by lommez** [comment]
Now is building perfectly!
But i'm some trouble to download the javascript files using requirejs.
Here is my tsconfig.json

`{
  "compilerOptions": {
    "module": "amd",
    "noImplicitAny": false,
    "noEmitOnError": true,
    "removeComments": false,
    "sourceMap": true,
    "target": "es5",
    "outDir": "typescript/generated"
  },
  "exclude": [
    "node_modules",
    "wwwroot"
  ]
}` 

So when my application is trying to download for example, the file TimeSpan.js from:
http://myApplication/typescript/libs/typescript-dotnet-amd/System/Time/TimeSpan.js 
that file can't be found because the physical files ares stored in <applicaton root>/libs/typescript-dotnet-amd.

Do you know if there any way to tell requirejs to download those files from that directory?

**Comment by electricessence** [comment]
@lommez YES!

**Comment by electricessence** [comment]
So there's some tricks in RequireJS.
You can set 'aliases' for any directory.

**Comment by electricessence** [comment]
So what I typically do... Is in my imports I will put
```typescript
import {TimeSpan} from 'typescript-dotnet-amd/System/Time/TimeSpan';
```

And by using the require config I can define an alias for:
```
requirejs.config({
    paths: {
        "typescript-dotnet-amd": "[ the path ]"
    },
});
```

**Comment by electricessence** [comment]
You can even omit the ```-amd``` from that point on...
The only caveat is that of course most people using TypeScript will want the types to come through automatically.  And as long as that works, then great.

**Comment by electricessence** [comment]
@lommez if you want to see this in action:
https://github.com/electricessence/TypeScript.NET/tree/master/tests/qunit
I added these qunit tests when I started to ensure that AMD continued to work and in the case of WebStorm everything works perfectly.  It resolves the types and everything.

**Comment by lommez** [comment]
Thanks so much! I'll check those tests

**Comment by electricessence** [comment]
@lommez You're welcome :)

**Comment by lommez** [comment]
@electricessence , now is working perfectly.
It was missing in my tsconfig the path for the typescript-dotnet-amd.
Congratulations on your excellent work.
