### ISSUE TITLE
Initializers are not allowed in ambient contexts

### ISSUE THREAD

**Issue by lommez** [electricessence/TypeScript.NET#54]
Hi, 
I´ve downloaded the latest version, typescript-dotnet-amd@4.7.13.
And the compiler is raising that exception:
"Error TS1039 Initializers are not allowed in ambient contexts."
On file typescript-dotnet-amd\System\ExceptionType.d.ts.
I'm using typescript 2.1.4.
Do you know why this is happening?
Thanks!

**Comment by electricessence** [comment]
@lommez investigating

**Comment by electricessence** [comment]
I would need to see an example of your code that is triggering this.
This file specifically is only there for respect to .NET .
There is nothing about this file that would cause an exception.

**Comment by lommez** [comment]
I'm going to investigate this better, because i just updated the typescript-dotnet and nothing more.

**Comment by lommez** [comment]
Is the bower version is up to date?

**Comment by lommez** [comment]
I found out what was the error. Visual Studio was running a older version of typescript.
Now i could build my project without a problem
