### ISSUE TITLE
Any body know how to add TypeScrip.NET to angular2 ?

### ISSUE THREAD

**Issue by oleksandrmelnychenko** [electricessence/TypeScript.NET#56]
I have used all packages and Environment.Js throw error that and use eval('required')

**Comment by oleksandrmelnychenko** [comment]
Collections types not working, Lazy, Integer, Task are working fine

**Comment by electricessence** [comment]
Interesting.  Ive used TypeScript .NET in Angular 2 without any issues before.
Can you verify the version of TS .NET you are using?
Is this in the browser or in Node?
I'm not sure where ```eval('required')``` is coming in since ```eval('require')``` is what it is actually doing.

**Comment by electricessence** [comment]
I've looked and all references in the code base to ```eval('required')``` are for ```eval('require')```;

**Comment by electricessence** [comment]
Ok here's the catch:
You want to use ```typescript-dotnet-commonjs``` as your dist version.
Because Angular2 should do all the browserify style bundling with it.

**Comment by electricessence** [comment]
So when you install TypeScript .NET from npm.  Use:

```npm install typescript-dotnet-commonjs --save```

**Comment by electricessence** [comment]
Let me know if that helps.  There may be some other config stuff you need to do to be sure angular2 knows where to pull from, but I pretty sure that's it.

**Comment by oleksandrmelnychenko** [comment]
![issue](https://cloud.githubusercontent.com/assets/7407215/22457972/144936ee-e7a3-11e6-9331-d0c2cbde1922.PNG)

**Comment by oleksandrmelnychenko** [comment]
![image](https://cloud.githubusercontent.com/assets/7407215/22457999/2f630374-e7a3-11e6-93f8-b2347dd18a17.png)

**Comment by oleksandrmelnychenko** [comment]
when i include IEnumerable it's break, for example i use Lazy<T> it;s okay, working, but LINQ not and many others libs also are throw this

**Comment by oleksandrmelnychenko** [comment]
I have used lasted angular CLI beta 26,

**Comment by electricessence** [comment]
Oh interesting.  You are using ES6?

**Comment by oleksandrmelnychenko** [comment]
yes

**Comment by electricessence** [comment]
And what's transpiling to ES5?  Something built in to Angular?

**Comment by electricessence** [comment]
I'm looking into this now.  Your issue probably doesn't happen with ES5.

**Comment by oleksandrmelnychenko** [comment]
![image](https://cloud.githubusercontent.com/assets/7407215/22477934/9a06fea4-e7f0-11e6-9049-b6164f50250a.png)

**Comment by oleksandrmelnychenko** [comment]
What interesting that, some types are working

**Comment by electricessence** [comment]
Ok so you ARE targeting ES5.  So you can't use "typescript-dotnet-es6".
You have to use "typescript-dotnet-commonjs" or "typescript-dotnet-umd".

**Comment by oleksandrmelnychenko** [comment]
i have used "typescript-dotnet-umd" at the beginning

**Comment by oleksandrmelnychenko** [comment]
https://1drv.ms/u/s!AlTIWb5-A76AhN18BO3U8rx-Wt9diQ

**Comment by electricessence** [comment]
The UMD version can be troublesome because of conflicts with WebPack etc.
Try -commonjs.

**Comment by electricessence** [comment]
Sorry, the Zip file is being flagged with a virus.  Can you share over github?

**Comment by electricessence** [comment]
Preferrably, just try ```typescript-dotnet-commonjs``` instead and let me know if that works.
My working Angular2 app uses it.

**Comment by oleksandrmelnychenko** [comment]
![image](https://cloud.githubusercontent.com/assets/7407215/22478461/935fa69e-e7f2-11e6-8b05-cd833881f80a.png)

**Comment by oleksandrmelnychenko** [comment]
![image](https://cloud.githubusercontent.com/assets/7407215/22478488/b773d816-e7f2-11e6-9680-86e559101627.png)

**Comment by electricessence** [comment]
@oleksandrmelnychenko Hmm... Not having a module loader ('require') is concerning.

**Comment by oleksandrmelnychenko** [comment]
https://github.com/oleksandrmelnychenko/ng2ForTest

**Comment by electricessence** [comment]
Ok.  So again, Webpack is giving me woes.  I can see here that it must be recompiling the code and stripping out 'require' references.  I'll need to look at this more.   Any chance you can turn off webpack for now?

**Comment by electricessence** [comment]
Oh wait.  It works now?

**Comment by oleksandrmelnychenko** [comment]
i dont hurry up with it, just want to use in my own company web app, so maybe you can fix it.

**Comment by electricessence** [comment]
So wait, with those two screenshots... Is it working or not?

**Comment by electricessence** [comment]
Oh I see.

**Comment by oleksandrmelnychenko** [comment]
on the second screenshot Task<T> is working, but if i use another type, for example LazyPromise<T> or Collection, it doesn't

**Comment by electricessence** [comment]
Well if you give me a few minutes, work with me, we'll fix this.
It doesn't take me but a second to redeploy.

**Comment by oleksandrmelnychenko** [comment]
sure

**Comment by electricessence** [comment]
I'm concerned that I'm unable to call for require :(
If webpack eliminates it from the loading context then 1) no dynamic loading, 2) some features will be disabled.  But I can definitely put a try catch on the eval.

**Comment by oleksandrmelnychenko** [comment]
I think you need also add EventAggregator in this framework, i can help if needed. It can be full tooling for all life cases :)

**Comment by electricessence** [comment]
Stand by.  Build pending.

**Comment by oleksandrmelnychenko** [comment]
no problem, sure

**Comment by electricessence** [comment]
You won't be able to call .linq or .linqAsync on any collection.  You'll have to use Enumerable(x) to get a linq object.

**Comment by oleksandrmelnychenko** [comment]
okay, but what about LazyPromise<T>, or some others types? Integer(1) is also okay

**Comment by oleksandrmelnychenko** [comment]
LinkedList<T> also not.

**Comment by electricessence** [comment]
Yeah, just hold on.  All should be well.

**Comment by electricessence** [comment]
I apologize, but I struggled with Webpack for a while but didn't run into any errors like this.  So I appreciate you reporting this to me so it can be fixed.

**Comment by electricessence** [comment]
All set.  4.7.14 is up on NPM.  Please update and try again.

**Comment by oleksandrmelnychenko** [comment]
okay, some mins

**Comment by oleksandrmelnychenko** [comment]
I think it's brilliant now

**Comment by oleksandrmelnychenko** [comment]
One thing more, i did dummy code, it's throw the exception, in core of framework, 
it can be good console will display it

**Comment by electricessence** [comment]
On the last comment, could you be more specific?

**Comment by oleksandrmelnychenko** [comment]
sure, let me prepare information

**Comment by oleksandrmelnychenko** [comment]
![exc](https://cloud.githubusercontent.com/assets/7407215/22482402/7bb44c02-e801-11e6-80e7-43d9607e8be0.png)

**Comment by oleksandrmelnychenko** [comment]
So i did non logical code and inside the framework, exception has been thrown, but it's not displayed in console. Sometimes it can help to reduce time fixing something or detect some defects.

**Comment by electricessence** [comment]
So did we fix this issue?  May I close?

**Comment by oleksandrmelnychenko** [comment]
everything is good, yes sure

________________________________
