### ISSUE TITLE
exports is not defined

### ISSUE THREAD

**Issue by Shekesh** [electricessence/TypeScript.NET#66]
I'm using your Linq library as a native ES6 module in Electron (typescript-dotnet-es6).
The module gets extracted by rollup.js.
The import looks like
`import Enumerable from 'typescript-dotnet-es6/System.Linq/Linq';`
Electron / chromium throws the error `Uncaught ReferenceError: exports is not defined`
The source of the error is in https://github.com/electricessence/TypeScript.NET/blob/3c5be8a3632d9e54532aed324459d59f283aca6b/dist/es6/System/Environment.js#L29
When I delete `Object.freeze(exports)` everything works fine.

**Comment by electricessence** [comment]
Investigating...

**Comment by electricessence** [comment]
I see...

**Comment by electricessence** [comment]
Will need a bit of time to fix as TS has somehow become wildly incompatible with the code I have.
It is an easy fix, it's just not easy to fix right this second.
I have branches in place, but they won't compile. :(

**Comment by electricessence** [comment]
Ok.  This is fixed.  Please verify at your leisure. Latest is now: 4.9.8

**Comment by Shekesh** [comment]
I can confirm it is fixed. Thank you very much :smile:
