### ISSUE TITLE
toString() in System/Text/StringBuilder does not work well

### ISSUE THREAD

**Issue by RYOSKATE** [electricessence/TypeScript.NET#69]
toString () always returns `null` whatever I append.
It seems to be because `_latest` always has the value of `null`.
(about dist/es6)

**Comment by electricessence** [comment]
@RYOSKATE Will fix immediately.

**Comment by electricessence** [comment]
https://github.com/electricessence/TypeScript.NET/blob/3ece39d04b83724383ea317764313298ee2a4d59/source/System/Text/StringBuilder.ts#L110

Bad comparison on line 110.

**Comment by electricessence** [comment]
https://www.npmjs.com/package/typescript-dotnet-umd

All fixed: https://github.com/electricessence/TypeScript.NET/commit/76049732c206a34b52896e265f69b10e19cc7b34

**Comment by electricessence** [comment]
@RYOSKATE Thank you so much for you submission!  Now that a test has been added, shouldn't have any issues.  Surprised this slipped through.  Also, .toString() if it worked, returned comma separated values!  Now it works properly. :)

**Comment by electricessence** [comment]
@RYOSKATE You're very welcome!
