### ISSUE TITLE
List<>.contains does not work if custom comparer

### ISSUE THREAD

**Issue by mavogt** [electricessence/TypeScript.NET#70]
Hi
I think I found a small bug:
I have a generic list with a custom comparer: 
![grafik](https://user-images.githubusercontent.com/14938503/42037592-16226db6-7ae9-11e8-9033-f96b1b57bef1.png)
The function "contains" does not work correctly because it does not respect the custom comparer. I think I found the error in your code in the System.Collections.Array.Utility class in the method indexOf():
![grafik](https://user-images.githubusercontent.com/14938503/42037925-db8d453a-7ae9-11e8-8f5b-ff64b4465134.png)
The marked if is evaluated to true and so it does just a normal "array.indexOf(item)".

Thanks a lot for that great library! 
Best regards
Martin Vogt

**Comment by electricessence** [comment]
@mavogt Will investigate today.

**Comment by electricessence** [comment]
This is a good catch.  Working on a fix now.

**Comment by electricessence** [comment]
version 4.11.0 published to NPM.
Compiled with TS 2.9.2
