### ISSUE TITLE
Regular Expression

### ISSUE THREAD

**Issue by vikaskeskar11** [electricessence/TypeScript.NET#73]
I am trying to execute `regex.matches(expression)` , but during execution I'm getting error as 

> Can not read length of undefined

I found the fix, but need's to edit the library

**Comment by electricessence** [comment]
Will investigate and fix.
Can you provide a sample expression that causes it?

**Comment by vikaskeskar11** [comment]
`\b(?<h>\d{1,2})((\:00)?(?<m>(\:\d{1,2}){0,2})) ?(AM\.|am\.|A\.M\.|AM|am)`
Regex

`5 AM`
`5AM`

Expression

**Comment by electricessence** [comment]
Great... will look into it today...

**Comment by electricessence** [comment]
This is now fixed.
You're lucky this was a simple change. :P
I've been rewriting the whole lib now that 3.x is out and it's incredibly painful to update the older version.
Hope that helps!!! Thanks for finding this!!!

**Comment by vikaskeskar11** [comment]
It's working fine now. Thanks
